when:
  - event: push
    branch:
      - main
      - develop
  - event: pull_request

variables:
  # Use the same Go version as specified in go.mod
  GOLANG_VERSION: "1.25"
  # TinyGo version as used in Dockerfile
  TINYGO_VERSION: "0.39.0"

steps:
  # Lint step - runs golangci-lint
  lint:
    image: golang:${GOLANG_VERSION}-alpine
    commands:
      - apk add --no-cache git
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - go mod download
      - echo "Generating templ templates..."
      - templ generate
      - echo "Running golangci-lint..."
      - golangci-lint run --timeout=5m
    when:
      - event: push
      - event: pull_request

  # Test step - runs unit tests with short flag
  test:
    image: golang:${GOLANG_VERSION}-alpine
    commands:
      - apk add --no-cache git ca-certificates tzdata
      - update-ca-certificates
      # Install TinyGo (required for tests that use sandbox functionality)
      - wget https://github.com/tinygo-org/tinygo/releases/download/v${TINYGO_VERSION}/tinygo${TINYGO_VERSION}.linux-amd64.tar.gz
      - tar -C /usr/local -xzf tinygo${TINYGO_VERSION}.linux-amd64.tar.gz
      - rm tinygo${TINYGO_VERSION}.linux-amd64.tar.gz
      - export PATH="/usr/local/tinygo/bin:${PATH}"
      - go mod download
      - echo "Running tests with -short flag..."
      - go test -short ./...
    when:
      - event: push
      - event: pull_request

  # Build step - compiles the main binary
  build:
    image: golang:${GOLANG_VERSION}-alpine
    commands:
      - apk add --no-cache git ca-certificates tzdata musl-gcc
      - update-ca-certificates
      # Install TinyGo (required for the project)
      - wget https://github.com/tinygo-org/tinygo/releases/download/v${TINYGO_VERSION}/tinygo${TINYGO_VERSION}.linux-amd64.tar.gz
      - tar -C /usr/local -xzf tinygo${TINYGO_VERSION}.linux-amd64.tar.gz
      - rm tinygo${TINYGO_VERSION}.linux-amd64.tar.gz
      - export PATH="/usr/local/tinygo/bin:${PATH}"
      # Download dependencies and build with static linking
      - go mod download
      - echo "Building main binary with static linking..."
      - CGO_ENABLED=1 CC=musl-gcc GOOS=linux go build -ldflags="-w -s -linkmode external -extldflags '-static'" -o scriptschnell ./cmd/scriptschnell
      - echo "Building debug HTML tool with static linking..."
      - CGO_ENABLED=1 CC=musl-gcc GOOS=linux go build -ldflags="-w -s -linkmode external -extldflags '-static'" -o debug_html ./cmd/debug_html
      - ls -la scriptschnell debug_html
    when:
      - event: push
      - event: pull_request