package tools

const (
	ToolNameReadFile             = "read_file"
	ToolNameReadFileSummarized   = "read_file_summarized"
	ToolNameCreateFile           = "create_file"
	ToolNameEditFile             = "edit_file"
	ToolNameShell                = "shell"
	ToolNameCommand              = "command"
	ToolNameStatusProgram        = "status_program"
	ToolNameWaitProgram          = "wait_program"
	ToolNameStopProgram          = "stop_program"
	ToolNameParallel             = "parallel_tool_execution"
	ToolNameGoSandbox            = "go_sandbox"
	ToolNameGoSandboxDomain      = "go_sandbox_domain"
	ToolNameWebSearch            = "web_search"
	ToolNameWebFetch             = "web_fetch"
	ToolNameToolSummarize        = "tool_summarize"
	ToolNameTodo                 = "todo"
	ToolNameSearchFiles          = "search_files"
	ToolNameSearchFileContent    = "search_file_content"
	ToolNameCodebaseInvestigator = "codebase_investigator"
	ToolNameValidateSyntax       = "validate_syntax"
	ToolNameLs                   = "list_dir"
	ToolNameSearchContextFiles   = "search_context_files"
	ToolNameGrepContextFiles     = "grep_context_files"
	ToolNameReadContextFile      = "read_context_file"
)
